# Generated by Django 2.2.8 on 2020-03-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_picture', '0011_auto_20190314_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='cms_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
