# Generated by Django 2.2.8 on 2020-07-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_picture', '0012_picture_cms_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='cms_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
